module.exports = [
  {
    name: "default",
    type: "postgres",
    host: "localhost",
    port: "5432",
    username: "prm",
    password: "admin",
    database: "prm",
    synchronize: false,
    logging: true,
    entities: ["src/entity/**/*.ts"],
    migrations: ["src/migration/**/*.ts"],
    subscribers: ["src/subscriber/**/*.ts"],
    cli: {
      entitiesDir: "src/entity",
      migrationsDir: "src/migration",
      subscribersDir: "src/subscriber",
    },
  },
  {
    name: "seed",
    type: "postgres",
    host: "localhost",
    port: "5432",
    username: "prm",
    password: "admin",
    database: "prm",
    synchronize: false,
    logging: true,
    entities: ["src/entity/**/*.ts"],
    migrations: ["src/seed/**/*.ts"],
    subscribers: ["src/subscriber/**/*.ts"],
    cli: {
      entitiesDir: "src/entity",
      migrationsDir: "src/seed",
      subscribersDir: "src/subscriber",
    },
  },
];
